import React, { useEffect, useState } from 'react';
import { CheckCircle2, LoaderCircle, MailCheck, ShieldCheck } from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { getRegistrationLinkById } from '../../services/firebase';
import { maskCPF } from '../../utils/formatters';
import { maskSelfRegistrationCep, maskSelfRegistrationPhone } from '../../utils/memberSelfRegistration';
import { ESTADOS_CIVIS, SEXOS } from '../../utils/pessoaForm';
import { confirmRegistrationEmailCodeOnServer, requestRegistrationEmailCodeOnServer, submitReusableRegistrationOnServer } from '../../services/firebaseFunctions';
import { PRIVACY_NOTICE_VERSION } from '../../utils/reusableRegistration';

const fieldClass = 'mt-1 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-purple-500 focus:ring-2 focus:ring-purple-100';
const labels = { masculino: 'Masculino', feminino: 'Feminino', outro: 'Outro', nao_informado: 'Prefiro não informar', solteiro: 'Solteiro(a)', casado: 'Casado(a)', uniao_estavel: 'União estável', separado: 'Separado(a)', divorciado: 'Divorciado(a)', viuvo: 'Viúvo(a)' };
const emptyAddress = { cep: '', logradouro: '', numero: '', complemento: '', bairro: '', cidade: '', uf: '' };
const initialForm = { nome: '', cpf: '', contato: '', email: '', dataNascimento: '', sexo: 'nao_informado', estadoCivil: 'nao_informado', endereco: emptyAddress, dadosCasa: { dataIngresso: '', batizadoCaesf: null, dataBatismoCaesf: '' } };

const Message = ({ sent, protocol }) => <main className="flex min-h-screen items-center justify-center bg-purple-50/50 p-4"><section className="w-full max-w-lg rounded-3xl bg-white p-8 text-center shadow-xl">{sent ? <CheckCircle2 className="mx-auto text-emerald-600" size={48}/> : <ShieldCheck className="mx-auto text-purple-600" size={48}/>}<h1 className="mt-4 text-xl font-black text-gray-900">{sent ? 'Solicitação enviada' : 'Link indisponível'}</h1><p className="mt-3 text-sm font-medium text-gray-600">{sent ? 'Seus dados foram enviados e aguardam análise da Casa Santa Fé.' : 'Este link é inválido, foi desativado, expirou ou atingiu o limite de cadastros.'}</p>{sent && protocol && <div className="mt-5 rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">Comprovante do aceite</p><p className="mt-1 break-all font-mono text-sm font-black text-emerald-900">{protocol}</p><p className="mt-2 text-xs text-emerald-700">Termos {PRIVACY_NOTICE_VERSION} · e-mail confirmado</p></div>}</section></main>;

export function ReusableRegistrationPage({ linkId }) {
  const [state, setState] = useState({ status: 'carregando', link: null });
  const [form, setForm] = useState(initialForm);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [acceptance, setAcceptance] = useState({ avisoPrivacidade: false, declaracaoVeracidade: false });
  const [emailProof, setEmailProof] = useState({ id: '', code: '', status: 'nao_enviado' });
  const [formStartedAt] = useState(() => Date.now());
  const [website, setWebsite] = useState('');
  useEffect(() => { let active = true; getRegistrationLinkById(linkId).then(result => active && setState(result)).catch(() => active && setState({ status: 'invalido', link: null })); return () => { active = false; }; }, [linkId]);
  if (state.status === 'carregando') return <main className="flex min-h-screen items-center justify-center bg-purple-50/50"><div className="text-center"><LoaderCircle className="mx-auto animate-spin text-purple-600"/><p className="mt-3 text-sm font-bold text-gray-500">Validando link...</p></div></main>;
  if (state.status === 'enviado') return <Message sent protocol={state.protocol}/>;
  if (state.status !== 'ativo' || !state.link) return <Message/>;
  const member = state.link.tipoCadastro === 'membro';
  const update = (key, value) => { setForm(current => ({ ...current, [key]: key === 'contato' ? maskSelfRegistrationPhone(value) : key === 'cpf' ? maskCPF(value) : value })); if (key === 'email') setEmailProof({ id: '', code: '', status: 'nao_enviado' }); };
  const updateAddress = (key, value) => setForm(current => ({ ...current, endereco: { ...current.endereco, [key]: key === 'cep' ? maskSelfRegistrationCep(value) : value } }));
  const updateHouse = (key, value) => setForm(current => ({ ...current, dadosCasa: { ...current.dadosCasa, [key]: value, ...(key === 'batizadoCaesf' && value === false ? { dataBatismoCaesf: '' } : {}) } }));
  const sendCode = async () => {
    setBusy(true); setError('');
    try { const result = await requestRegistrationEmailCodeOnServer(linkId, form.email); setEmailProof({ id: result.verificationId, code: '', status: 'enviado' }); }
    catch (sendError) { setError(sendError?.code === 'functions/resource-exhausted' ? 'Aguarde um minuto antes de pedir outro código.' : 'Não foi possível enviar o código. Confira o e-mail e tente novamente.'); }
    finally { setBusy(false); }
  };
  const confirmCode = async () => {
    setBusy(true); setError('');
    try { await confirmRegistrationEmailCodeOnServer(emailProof.id, emailProof.code); setEmailProof(current => ({ ...current, status: 'confirmado' })); }
    catch { setError('Código inválido ou expirado. Confira o e-mail ou solicite outro código.'); }
    finally { setBusy(false); }
  };
  const submit = async event => {
    event.preventDefault(); setBusy(true); setError('');
    try { const result = await submitReusableRegistrationOnServer({ linkId, formStartedAt, website, data: { ...form, aceite: acceptance, verificacaoEmailId: emailProof.id } }); setState({ status: 'enviado', link: state.link, protocol: result.id }); }
    catch (submitError) {
      const messages = { NOME_OBRIGATORIO: 'Informe seu nome.', CONTATO_OBRIGATORIO: 'Informe um telefone com DDD.', CPF_INVALIDO: 'Informe um CPF válido.', EMAIL_OBRIGATORIO: 'Informe um e-mail válido.', EMAIL_INVALIDO: 'Informe um e-mail válido.', EMAIL_NAO_CONFIRMADO: 'Confirme seu e-mail com o código recebido.', AVISO_PRIVACIDADE_OBRIGATORIO: 'Leia e aceite o Aviso de Privacidade.', DECLARACAO_VERACIDADE_OBRIGATORIA: 'Confirme a declaração de veracidade.', AUTOCADASTRO_BATIZADO_OBRIGATORIO: 'Informe se foi batizado na CAESF.', AUTOCADASTRO_DATA_BATISMO_OBRIGATORIA: 'Informe a data de batismo.' };
      setError(submitError?.code === 'functions/resource-exhausted' ? 'Foram feitas muitas tentativas. Aguarde um pouco e tente novamente.' : messages[submitError.message] || 'Não foi possível enviar. Confira os dados ou tente novamente.');
    } finally { setBusy(false); }
  };
  return <main className="min-h-screen bg-purple-50/50 px-4 py-8 sm:py-12"><form onSubmit={submit} className="mx-auto w-full max-w-3xl space-y-6 rounded-3xl bg-white p-5 shadow-xl sm:p-8"><label className="absolute -left-[10000px]" aria-hidden="true">Não preencha este campo<input tabIndex={-1} autoComplete="off" value={website} onChange={event => setWebsite(event.target.value)}/></label><header className="border-b border-gray-100 pb-5"><p className="text-xs font-black uppercase tracking-widest text-purple-600">Casa Santa Fé</p><h1 className="mt-1 text-2xl font-black text-gray-900">{state.link.nome}</h1><p className="mt-2 text-sm text-gray-500">{member ? 'Cadastro completo de Membro para análise.' : 'Cadastro simplificado de Consulente para análise.'}</p></header>
    <section><h2 className="font-black text-gray-900">Identificação e contato</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Nome *<input required maxLength={150} className={fieldClass} value={form.nome} onChange={e => update('nome', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">Contato *<input required maxLength={16} inputMode="tel" className={fieldClass} value={form.contato} onChange={e => update('contato', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">CPF *<input required maxLength={14} inputMode="numeric" className={fieldClass} value={form.cpf} onChange={e => update('cpf', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">E-mail {member ? '*' : '(opcional)'}<input type="email" required={member} className={fieldClass} value={form.email} onChange={e => update('email', e.target.value)}/></label></div></section>
    {member && <><section><h2 className="font-black text-gray-900">Dados pessoais</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Data de nascimento<input type="date" className={fieldClass} value={form.dataNascimento} onChange={e => update('dataNascimento', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">Sexo<select className={fieldClass} value={form.sexo} onChange={e => update('sexo', e.target.value)}>{SEXOS.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></label><label className="text-xs font-bold text-gray-600 sm:col-span-2">Estado civil<select className={fieldClass} value={form.estadoCivil} onChange={e => update('estadoCivil', e.target.value)}>{ESTADOS_CIVIS.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></label></div></section><section><h2 className="font-black text-gray-900">Endereço</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{[['cep', 'CEP'], ['logradouro', 'Logradouro'], ['numero', 'Número'], ['complemento', 'Complemento'], ['bairro', 'Bairro'], ['cidade', 'Cidade'], ['uf', 'UF']].map(([key, label]) => <label key={key} className={`text-xs font-bold text-gray-600 ${key === 'logradouro' ? 'sm:col-span-2' : ''}`}>{label}<input className={fieldClass} value={form.endereco[key]} maxLength={key === 'uf' ? 2 : 120} onChange={e => updateAddress(key, e.target.value)}/></label>)}</div></section><section><h2 className="font-black text-gray-900">Dados da Casa</h2><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Data de entrada<input type="date" className={fieldClass} value={form.dadosCasa.dataIngresso} onChange={e => updateHouse('dataIngresso', e.target.value)}/></label><fieldset><legend className="text-xs font-bold text-gray-600">Batizado na CAESF? *</legend><div className="mt-3 flex gap-5 text-sm font-bold"><label><input type="radio" required checked={form.dadosCasa.batizadoCaesf === true} onChange={() => updateHouse('batizadoCaesf', true)}/> Sim</label><label><input type="radio" required checked={form.dadosCasa.batizadoCaesf === false} onChange={() => updateHouse('batizadoCaesf', false)}/> Não</label></div></fieldset>{form.dadosCasa.batizadoCaesf === true && <label className="text-xs font-bold text-gray-600 sm:col-span-2">Data de batismo *<input required type="date" className={fieldClass} value={form.dadosCasa.dataBatismoCaesf} onChange={e => updateHouse('dataBatismoCaesf', e.target.value)}/></label>}</div></section></>}
    {member && <section className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4"><div className="flex items-center gap-2"><MailCheck className="text-indigo-600" size={20}/><h2 className="font-black text-indigo-950">Confirmar e-mail</h2></div><p className="mt-2 text-xs text-indigo-700">Enviaremos um código de 6 números para o e-mail informado acima. Ele será válido por 10 minutos.</p><div className="mt-3 space-y-3">{emailProof.status !== 'confirmado' && <Button type="button" variant="secondary" disabled={busy || !form.email} onClick={sendCode}>{emailProof.status === 'enviado' ? 'Reenviar código' : 'Enviar código'}</Button>}{emailProof.status === 'enviado' && <div className="grid max-w-sm grid-cols-[minmax(0,1fr)_auto] gap-2"><input aria-label="Código de confirmação" inputMode="numeric" maxLength={6} className={`${fieldClass} !mt-0 text-center font-mono tracking-[0.35em]`} placeholder="000000" value={emailProof.code} onChange={e => setEmailProof(current => ({ ...current, code: e.target.value.replace(/\D/g, '').slice(0, 6) }))}/><Button type="button" className="min-w-32 px-5" disabled={busy || emailProof.code.length !== 6} onClick={confirmCode}>Confirmar código</Button></div>}{emailProof.status === 'confirmado' && <p className="flex items-center gap-2 text-sm font-black text-emerald-700"><CheckCircle2 size={18}/> E-mail confirmado</p>}</div></section>}
    <section className="rounded-2xl border border-purple-100 p-4"><details><summary className="cursor-pointer font-black text-purple-800">Aviso de Privacidade — leia antes de continuar</summary><div className="mt-3 space-y-2 text-xs leading-relaxed text-gray-600"><p>A Casa de Auxílio Santa Fé utilizará os dados informados para identificar você, analisar e manter seu cadastro, organizar atividades institucionais e realizar comunicações relacionadas à Casa.</p><p>O cadastro pode conter dados pessoais sensíveis relacionados à participação religiosa. O acesso será limitado às pessoas autorizadas e os dados serão mantidos somente pelo período necessário às finalidades institucionais e obrigações aplicáveis.</p><p>Você pode solicitar confirmação do tratamento, acesso, correção, revogação do consentimento e demais direitos previstos na LGPD pelo e-mail casadeauxiliosantafe@gmail.com.</p><p>Versão do aviso: {PRIVACY_NOTICE_VERSION}</p></div></details><div className="mt-4 space-y-3"><label className="flex items-start gap-3 text-sm font-medium text-gray-700"><input type="checkbox" required className="mt-1" checked={acceptance.avisoPrivacidade} onChange={e => setAcceptance(current => ({ ...current, avisoPrivacidade: e.target.checked }))}/><span>Li o Aviso de Privacidade e autorizo, de forma específica, o tratamento dos dados pessoais e sensíveis necessários ao meu cadastro e às atividades da Casa.</span></label><label className="flex items-start gap-3 text-sm font-medium text-gray-700"><input type="checkbox" required className="mt-1" checked={acceptance.declaracaoVeracidade} onChange={e => setAcceptance(current => ({ ...current, declaracaoVeracidade: e.target.checked }))}/><span>Declaro que os dados informados são verdadeiros e confirmo minha solicitação de cadastro.</span></label></div></section>
    <p className="rounded-2xl bg-amber-50 p-4 text-xs font-bold text-amber-800">O envio não cria cadastro definitivo nem concede acesso ao sistema. A administração analisará os dados.</p>{error && <p role="alert" className="text-sm font-bold text-rose-600">{error}</p>}<Button type="submit" variant="purple" busy={busy} disabled={member && emailProof.status !== 'confirmado'} className="w-full">Enviar para análise</Button></form></main>;
}
