import React, { useEffect, useState } from 'react';
import { CheckCircle2, LoaderCircle, ShieldCheck } from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { getRegistrationLinkById, submitReusableRegistration } from '../../services/firebase';
import { maskCPF } from '../../utils/formatters';
import { maskSelfRegistrationCep, maskSelfRegistrationPhone } from '../../utils/memberSelfRegistration';
import { ESTADOS_CIVIS, SEXOS } from '../../utils/pessoaForm';

const fieldClass = 'mt-1 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-purple-500 focus:ring-2 focus:ring-purple-100';
const labels = { masculino: 'Masculino', feminino: 'Feminino', outro: 'Outro', nao_informado: 'Prefiro não informar', solteiro: 'Solteiro(a)', casado: 'Casado(a)', uniao_estavel: 'União estável', separado: 'Separado(a)', divorciado: 'Divorciado(a)', viuvo: 'Viúvo(a)' };
const emptyAddress = { cep: '', logradouro: '', numero: '', complemento: '', bairro: '', cidade: '', uf: '' };
const initialForm = { nome: '', cpf: '', contato: '', email: '', dataNascimento: '', sexo: 'nao_informado', estadoCivil: 'nao_informado', endereco: emptyAddress, dadosCasa: { dataIngresso: '', batizadoCaesf: null, dataBatismoCaesf: '' } };

const Message = ({ sent }) => <main className="flex min-h-screen items-center justify-center bg-purple-50/50 p-4"><section className="w-full max-w-lg rounded-3xl bg-white p-8 text-center shadow-xl">{sent ? <CheckCircle2 className="mx-auto text-emerald-600" size={48}/> : <ShieldCheck className="mx-auto text-purple-600" size={48}/>}<h1 className="mt-4 text-xl font-black text-gray-900">{sent ? 'Solicitação enviada' : 'Link indisponível'}</h1><p className="mt-3 text-sm font-medium text-gray-600">{sent ? 'Seus dados foram enviados e aguardam análise da Casa Santa Fé.' : 'Este link é inválido, foi desativado, expirou ou atingiu o limite de cadastros.'}</p></section></main>;

export function ReusableRegistrationPage({ linkId }) {
  const [state, setState] = useState({ status: 'carregando', link: null });
  const [form, setForm] = useState(initialForm);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; getRegistrationLinkById(linkId).then(result => active && setState(result)).catch(() => active && setState({ status: 'invalido', link: null })); return () => { active = false; }; }, [linkId]);
  if (state.status === 'carregando') return <main className="flex min-h-screen items-center justify-center bg-purple-50/50"><div className="text-center"><LoaderCircle className="mx-auto animate-spin text-purple-600"/><p className="mt-3 text-sm font-bold text-gray-500">Validando link...</p></div></main>;
  if (state.status === 'enviado') return <Message sent/>;
  if (state.status !== 'ativo' || !state.link) return <Message/>;
  const member = state.link.tipoCadastro === 'membro';
  const update = (key, value) => setForm(current => ({ ...current, [key]: key === 'contato' ? maskSelfRegistrationPhone(value) : key === 'cpf' ? maskCPF(value) : value }));
  const updateAddress = (key, value) => setForm(current => ({ ...current, endereco: { ...current.endereco, [key]: key === 'cep' ? maskSelfRegistrationCep(value) : value } }));
  const updateHouse = (key, value) => setForm(current => ({ ...current, dadosCasa: { ...current.dadosCasa, [key]: value, ...(key === 'batizadoCaesf' && value === false ? { dataBatismoCaesf: '' } : {}) } }));
  const submit = async event => {
    event.preventDefault(); setBusy(true); setError('');
    try { await submitReusableRegistration({ linkId, data: form }); setState({ status: 'enviado', link: state.link }); }
    catch (submitError) {
      const messages = { NOME_OBRIGATORIO: 'Informe seu nome.', CONTATO_OBRIGATORIO: 'Informe um telefone com DDD.', CPF_INVALIDO: 'Informe um CPF válido.', EMAIL_OBRIGATORIO: 'Informe um e-mail válido.', EMAIL_INVALIDO: 'Informe um e-mail válido.', AUTOCADASTRO_BATIZADO_OBRIGATORIO: 'Informe se foi batizado na CAESF.', AUTOCADASTRO_DATA_BATISMO_OBRIGATORIA: 'Informe a data de batismo.' };
      setError(messages[submitError.message] || 'Não foi possível enviar. Confira os dados ou tente novamente.');
    } finally { setBusy(false); }
  };
  return <main className="min-h-screen bg-purple-50/50 px-4 py-8 sm:py-12"><form onSubmit={submit} className="mx-auto w-full max-w-3xl space-y-6 rounded-3xl bg-white p-5 shadow-xl sm:p-8"><header className="border-b border-gray-100 pb-5"><p className="text-xs font-black uppercase tracking-widest text-purple-600">Casa Santa Fé</p><h1 className="mt-1 text-2xl font-black text-gray-900">{state.link.nome}</h1><p className="mt-2 text-sm text-gray-500">{member ? 'Cadastro completo de Membro para análise.' : 'Cadastro simplificado de Consulente para análise.'}</p></header>
    <section><h2 className="font-black text-gray-900">Identificação e contato</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Nome *<input required maxLength={150} className={fieldClass} value={form.nome} onChange={e => update('nome', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">Contato *<input required maxLength={16} inputMode="tel" className={fieldClass} value={form.contato} onChange={e => update('contato', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">CPF *<input required maxLength={14} inputMode="numeric" className={fieldClass} value={form.cpf} onChange={e => update('cpf', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">E-mail {member ? '*' : '(opcional)'}<input type="email" required={member} className={fieldClass} value={form.email} onChange={e => update('email', e.target.value)}/></label></div></section>
    {member && <><section><h2 className="font-black text-gray-900">Dados pessoais</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Data de nascimento<input type="date" className={fieldClass} value={form.dataNascimento} onChange={e => update('dataNascimento', e.target.value)}/></label><label className="text-xs font-bold text-gray-600">Sexo<select className={fieldClass} value={form.sexo} onChange={e => update('sexo', e.target.value)}>{SEXOS.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></label><label className="text-xs font-bold text-gray-600 sm:col-span-2">Estado civil<select className={fieldClass} value={form.estadoCivil} onChange={e => update('estadoCivil', e.target.value)}>{ESTADOS_CIVIS.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></label></div></section><section><h2 className="font-black text-gray-900">Endereço</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{[['cep', 'CEP'], ['logradouro', 'Logradouro'], ['numero', 'Número'], ['complemento', 'Complemento'], ['bairro', 'Bairro'], ['cidade', 'Cidade'], ['uf', 'UF']].map(([key, label]) => <label key={key} className={`text-xs font-bold text-gray-600 ${key === 'logradouro' ? 'sm:col-span-2' : ''}`}>{label}<input className={fieldClass} value={form.endereco[key]} maxLength={key === 'uf' ? 2 : 120} onChange={e => updateAddress(key, e.target.value)}/></label>)}</div></section><section><h2 className="font-black text-gray-900">Dados da Casa</h2><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Data de entrada<input type="date" className={fieldClass} value={form.dadosCasa.dataIngresso} onChange={e => updateHouse('dataIngresso', e.target.value)}/></label><fieldset><legend className="text-xs font-bold text-gray-600">Batizado na CAESF? *</legend><div className="mt-3 flex gap-5 text-sm font-bold"><label><input type="radio" required checked={form.dadosCasa.batizadoCaesf === true} onChange={() => updateHouse('batizadoCaesf', true)}/> Sim</label><label><input type="radio" required checked={form.dadosCasa.batizadoCaesf === false} onChange={() => updateHouse('batizadoCaesf', false)}/> Não</label></div></fieldset>{form.dadosCasa.batizadoCaesf === true && <label className="text-xs font-bold text-gray-600 sm:col-span-2">Data de batismo *<input required type="date" className={fieldClass} value={form.dadosCasa.dataBatismoCaesf} onChange={e => updateHouse('dataBatismoCaesf', e.target.value)}/></label>}</div></section></>}
    <p className="rounded-2xl bg-amber-50 p-4 text-xs font-bold text-amber-800">O envio não cria cadastro definitivo nem concede acesso ao sistema. A administração analisará os dados.</p>{error && <p role="alert" className="text-sm font-bold text-rose-600">{error}</p>}<Button type="submit" variant="purple" busy={busy} className="w-full">Enviar para análise</Button></form></main>;
}
