import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Archive, BookOpen, Download, Eye, FileDown, LockKeyhole, RefreshCcw, ShieldCheck, ShieldX } from 'lucide-react';
import { getAppCollection, getAppDoc, onSnapshot } from '../../services/firebase';
import { archiveBookVolumeOnServer, getBookVolumeDownloadOnServer, manageBookVolumeOnServer, refreshBookRecordOnServer, resetArchivedBookVolumeForHmlOnServer, verifyBookVolumeIntegrityOnServer } from '../../services/firebaseFunctions';
import { Button } from '../../components/ui/Button';
import { useToast } from '../../components/ui/useToast';
import { buildBookAnnualIndex } from '../../utils/bookAnnualIndex';
import { buildBookVerificationUrl } from '../../utils/bookVerification';
import QRCode from 'qrcode';

const dateValue = value => value?.toDate?.() || (value ? new Date(value) : null);
const formatDate = value => { const date = dateValue(value); return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('pt-BR') : '—'; };
const formatTime = value => { const date = dateValue(value); return date && !Number.isNaN(date.getTime()) ? date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '—'; };
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char]);
const memberWithCpf = person => person.ativo !== false && String(person.vinculo || person.tipoPessoa || '').toLowerCase().includes('membro') && /^\d{11}$/.test(String(person.cpf || '').replace(/\D/g, ''));
const monthLabel = competence => { const match = /^(\d{4})-(\d{2})$/.exec(String(competence || '')); return match ? new Date(Number(match[1]), Number(match[2]) - 1, 1).toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' }) : 'período legado'; };
const isHmlEnvironment = import.meta.env.MODE === 'hml';
const fileAsBase64 = file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); });
const recordIssues = record => {
  if (!Array.isArray(record.atendimentos)) return ['Sem detalhamento individual'];
  const issues = [];
  record.atendimentos.forEach(item => {
    if (!item.nome || item.nome === 'Nome não informado') issues.push('Pessoa sem nome');
    if (!item.servicos?.length) issues.push(`${item.nome || 'Pessoa'} sem serviço`);
    if (item.status === 'Concluído' && (!item.horaChegada || !item.horaConclusao)) issues.push(`${item.nome || 'Pessoa'} sem horário completo`);
  });
  return [...new Set(issues)];
};

const printVolume = async (volume, records) => {
  const popup = window.open('', '_blank'); if (!popup) throw new Error('POPUP_BLOQUEADO'); popup.opener = null;
  const logoUrl = `${window.location.origin}/logo_santa_fe.png`;
  const ordered = [...records].sort((a, b) => (dateValue(a.dataAtendimento)?.getTime() || 0) - (dateValue(b.dataAtendimento)?.getTime() || 0));
  const dailyRows = ordered.map(record => `<tr><td>${escapeHtml(formatDate(record.dataAtendimento))}</td><td>${escapeHtml(record.trabalho)}</td><td>${escapeHtml(record.dirigenteResponsavel?.nome)}</td><td>${Number(record.quantidadeAtendimentos || 0)}</td><td>${escapeHtml((record.trabalhadores || []).map(item => `${item.nome} (${item.funcaoNome || item.tipo || 'trabalhador'})`).join(', '))}</td></tr>`).join('');
  const attendanceRows = ordered.flatMap(record => (record.atendimentos || []).map(item => `<tr><td>${escapeHtml(formatDate(record.dataAtendimento))}</td><td>${escapeHtml(item.nome)}</td><td>${escapeHtml((item.servicos || []).map(service => service.nome).join(', ') || record.trabalho)}</td><td>${escapeHtml(item.status)}</td><td>${escapeHtml(formatTime(item.horaChegada))}</td><td>${escapeHtml(formatTime(item.horaConclusao))}</td></tr>`)).join('');
  const verificationUrl = buildBookVerificationUrl(window.location.origin, volume.codigoVerificacao);
  const qrCode = await QRCode.toDataURL(verificationUrl, { width: 220, margin: 1, errorCorrectionLevel: 'H', color: { dark: '#111827', light: '#ffffff' } });
  const seal = volume.status === 'arquivado' ? 'VOLUME ASSINADO E ARQUIVADO' : 'VOLUME ENCERRADO — AGUARDANDO ASSINATURA';
  const signatureArea = volume.status === 'arquivado' ? `<p><strong>PDF arquivado:</strong> ${escapeHtml(volume.assinatura?.codigoEvidencia || 'registro anterior à versão 26D')}</p>` : '<section class="signature"><strong>ESPAÇO RESERVADO PARA ASSINATURA ELETRÔNICA GOV.BR</strong><p>Posicione a assinatura visual da dirigente dentro desta área.</p></section>';
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><title>Livro Mediúnico — Volume ${Number(volume.numero)}</title><style>body{font:13px Arial;padding:24px}.header{text-align:center;page-break-inside:avoid}.logo{width:78px;height:78px;object-fit:contain}.header h1{margin:5px 0}.header h2{margin:4px 0 14px}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border:1px solid #aaa;padding:7px;text-align:left}.code{font-family:monospace;word-break:break-all;font-size:11px}.verify{display:flex;align-items:center;gap:10px;border:1px solid #4338ca;border-radius:8px;padding:8px;margin-top:16px;page-break-inside:avoid}.verify p{margin:4px 0}.verify img{width:72px;height:72px;flex:0 0 72px}.seal{display:inline-block;border:2px solid #047857;color:#047857;padding:7px 12px;font-weight:bold;border-radius:8px}.signature{min-height:150px;border:2px dashed #64748b;border-radius:10px;margin-top:22px;padding:14px;text-align:center;color:#475569;page-break-inside:avoid}.signature p{margin-top:8px;font-size:12px}@media print{button{display:none}.header,.verify,.signature{break-inside:avoid}}</style></head><body><header class="header"><img class="logo" src="${escapeHtml(logoUrl)}" alt="Logo da Casa de Auxílio Santa Fé"/><h1>Casa de Auxílio Santa Fé</h1><h2>Livro Mediúnico — Volume ${Number(volume.numero)} — ${escapeHtml(monthLabel(volume.competencia))}</h2></header><p class="seal">${escapeHtml(seal)}</p><p>Registros: ${ordered.length} · Atendimentos: ${ordered.reduce((sum, item) => sum + Number(item.quantidadeAtendimentos || 0), 0)}</p><h3>Fechamentos diários</h3><table><thead><tr><th>Data</th><th>Trabalho</th><th>Responsável</th><th>Atendimentos</th><th>Trabalhadores</th></tr></thead><tbody>${dailyRows}</tbody></table><h3>Pessoas atendidas</h3>${attendanceRows ? `<table><thead><tr><th>Data</th><th>Nome</th><th>Atendimento</th><th>Situação</th><th>Chegada</th><th>Conclusão</th></tr></thead><tbody>${attendanceRows}</tbody></table>` : '<p>Sem detalhamento individual.</p>'}<div class="verify"><img src="${qrCode}" alt="QR Code de verificação"/><div><strong>Verifique a autenticidade</strong><p>Código: <span class="code">${escapeHtml(volume.codigoVerificacao)}</span></p><p class="code">${escapeHtml(verificationUrl)}</p></div></div><p class="code"><strong>SHA-256:</strong> ${escapeHtml(volume.hashIntegridade || 'Disponível após o encerramento')}</p>${signatureArea}<button onclick="window.print()">Salvar ou imprimir PDF</button></body></html>`);
  popup.document.close(); popup.focus();
};

const printSignatureReceipt = volume => {
  const popup = window.open('', '_blank'); if (!popup) throw new Error('POPUP_BLOQUEADO'); popup.opener = null;
  const logoUrl = `${window.location.origin}/logo_santa_fe.png`;
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><title>Comprovante de assinatura — Volume ${Number(volume.numero)}</title><style>body{font:14px Arial;max-width:850px;margin:auto;padding:32px}header{text-align:center}header img{width:78px;height:78px;object-fit:contain}h1,h2{margin:5px}.box{border:1px solid #aaa;border-radius:10px;padding:16px;margin:18px 0}.code{font-family:monospace;word-break:break-all}@media print{button{display:none}}</style></head><body><header><img src="${escapeHtml(logoUrl)}" alt="Logo da Casa de Auxílio Santa Fé"/><h1>Casa de Auxílio Santa Fé</h1><h2>Comprovante de arquivamento do PDF assinado</h2></header><div class="box"><p><strong>Volume:</strong> ${Number(volume.numero)} — ${escapeHtml(monthLabel(volume.competencia))}</p><p><strong>Dirigente declarada:</strong> ${escapeHtml(volume.assinatura?.nome || 'Não informada')} (${escapeHtml(volume.assinatura?.papel || 'responsável')})</p><p><strong>CPF protegido:</strong> final ${escapeHtml(volume.assinatura?.cpfFinal || '—')}</p><p><strong>Data do arquivamento:</strong> ${escapeHtml(formatDate(volume.assinadoEm))}</p><p><strong>Método:</strong> ${volume.assinatura?.metodo === 'gov_br_manual' ? 'PDF assinado externamente pelo GOV.BR' : 'Registro institucional anterior'}</p><p><strong>Código do volume:</strong> <span class="code">${escapeHtml(volume.codigoVerificacao || '—')}</span></p><p><strong>Código da evidência:</strong> <span class="code">${escapeHtml(volume.assinatura?.codigoEvidencia || 'Registro anterior à versão 26D')}</span></p><p><strong>Hash da evidência:</strong> <span class="code">${escapeHtml(volume.assinatura?.evidenciaHash || 'Não disponível para registro legado')}</span></p><p><strong>Hash do arquivo:</strong> <span class="code">${escapeHtml(volume.arquivo?.hashSha256 || '—')}</span></p><p><strong>Hash do conteúdo:</strong> <span class="code">${escapeHtml(volume.hashIntegridade || '—')}</span></p></div><p>O sistema detectou uma assinatura digital incorporada e preservou o PDF recebido sem modificá-lo. A autenticidade do certificado deve ser consultada no serviço VALIDAR do ITI.</p><button onclick="window.print()">Salvar ou imprimir comprovante</button></body></html>`);
  popup.document.close(); popup.focus();
};

const printAnnualIndex = (summary, definitive) => {
  const statusLabel = { sem_movimento: 'Sem movimento', aberto: 'Aberto', encerrado: 'Aguardando assinatura', arquivado: 'Assinado' };
  const rows = summary.months.map(item => `<tr><td>${escapeHtml(new Date(Number(summary.year), Number(item.month) - 1, 1).toLocaleDateString('pt-BR', { month: 'long' }))}</td><td>${escapeHtml(statusLabel[item.status] || item.status)}</td><td>${item.days}</td><td>${item.attendances}</td><td class="code">${escapeHtml(item.verificationCode || '—')}</td></tr>`).join('');
  const popup = window.open('', '_blank'); if (!popup) throw new Error('POPUP_BLOQUEADO'); popup.opener = null;
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><title>Índice anual ${summary.year}</title><style>body{font:14px Arial;padding:28px}h1,h2{text-align:center}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{border:1px solid #aaa;padding:8px;text-align:left}.code{font-family:monospace}@media print{button{display:none}}</style></head><body><h1>Casa de Auxílio Santa Fé</h1><h2>Índice Anual do Livro Mediúnico — ${summary.year}</h2><p><strong>Tipo:</strong> ${definitive ? 'Definitivo' : 'Prévia para conferência'}</p><p><strong>Dias registrados:</strong> ${summary.totalDays} · <strong>Atendimentos:</strong> ${summary.totalAttendances}</p><table><thead><tr><th>Mês</th><th>Situação</th><th>Dias</th><th>Atendimentos</th><th>Código de integridade</th></tr></thead><tbody>${rows}</tbody></table>${definitive ? '<p>Todos os volumes com movimento deste ano foram assinados e arquivados.</p>' : `<p>Documento provisório. Existem ${summary.pendingCount} volume(s) pendente(s).</p>`}<button onclick="window.print()">Salvar ou imprimir PDF</button></body></html>`);
  popup.document.close(); popup.focus();
};

export const BookVolumesPanel = () => {
  const [volumes, setVolumes] = useState([]); const [records, setRecords] = useState([]); const [people, setPeople] = useState([]); const [responsibles, setResponsibles] = useState(null);
  const [busy, setBusy] = useState(false); const [archiveDraft, setArchiveDraft] = useState(null); const [expandedVolumeId, setExpandedVolumeId] = useState('');
  const [integrityChecks, setIntegrityChecks] = useState({});
  const [yearFilter, setYearFilter] = useState('todos'); const [monthFilter, setMonthFilter] = useState('todos'); const [correction, setCorrection] = useState(null); const toast = useToast();
  useEffect(() => {
    const unsubs = [
      onSnapshot(getAppCollection('livro_mediunico_volumes'), snapshot => setVolumes(snapshot.docs.map(item => ({ id: item.id, ...item.data() })))),
      onSnapshot(getAppCollection('livro_mediunico_registros'), snapshot => setRecords(snapshot.docs.map(item => ({ id: item.id, ...item.data() })))),
      onSnapshot(getAppCollection('pessoas'), snapshot => setPeople(snapshot.docs.map(item => ({ id: item.id, ...item.data() })).filter(memberWithCpf))),
      onSnapshot(getAppDoc('config_livro_mediunico', 'responsaveis'), snapshot => setResponsibles(snapshot.data() || null)),
    ];
    return () => unsubs.forEach(unsub => unsub());
  }, []);
  const ordered = useMemo(() => [...volumes].sort((a, b) => Number(b.numero) - Number(a.numero)), [volumes]);
  const years = useMemo(() => [...new Set(ordered.map(item => String(item.competencia || item.periodoInicio || '').slice(0, 4)).filter(Boolean))].sort().reverse(), [ordered]);
  const visibleVolumes = useMemo(() => ordered.filter(item => { const key = String(item.competencia || item.periodoInicio || ''); return (yearFilter === 'todos' || key.startsWith(yearFilter)) && (monthFilter === 'todos' || key.slice(5, 7) === monthFilter); }), [ordered, yearFilter, monthFilter]);
  const dashboardYear = yearFilter === 'todos' ? years[0] || String(new Date().getFullYear()) : yearFilter;
  const annualMonths = useMemo(() => Array.from({ length: 12 }, (_, index) => {
    const month = String(index + 1).padStart(2, '0'); const volume = ordered.find(item => String(item.competencia || item.periodoInicio || '').startsWith(`${dashboardYear}-${month}`));
    return { month, volume, label: new Date(Number(dashboardYear), index, 1).toLocaleDateString('pt-BR', { month: 'short' }) };
  }), [ordered, dashboardYear]);
  const annualTotals = useMemo(() => annualMonths.reduce((totals, item) => ({ records: totals.records + Number(item.volume?.quantidadeRegistros || 0), attendances: totals.attendances + Number(item.volume?.quantidadeAtendimentos || 0), pending: totals.pending + (item.volume?.status === 'encerrado' ? 1 : 0), signed: totals.signed + (item.volume?.status === 'arquivado' ? 1 : 0) }), { records: 0, attendances: 0, pending: 0, signed: 0 }), [annualMonths]);
  const annualIndex = useMemo(() => buildBookAnnualIndex({ year: dashboardYear, volumes: ordered, records }), [dashboardYear, ordered, records]);
  const eligibleSigners = useMemo(() => people.filter(person => [responsibles?.titularPessoaId, responsibles?.substitutaPessoaId].includes(person.id)), [people, responsibles]);
  const open = ordered.find(item => item.status === 'aberto');
  const executeClose = async () => { if (!window.confirm('Encerrar este mês agora? Gere o PDF somente depois de concluir todos os atendimentos do mês.')) return; setBusy(true); try { const result = await manageBookVolumeOnServer('close'); toast.success(`Volume ${result.numero} encerrado.`); } catch (error) { console.error(error); toast.error(String(error?.message || '').includes('VOLUME_SEM_REGISTROS') ? 'O volume ainda não possui registros.' : 'Não foi possível encerrar o mês.'); } finally { setBusy(false); } };
  const refreshRecord = async () => { if (!correction?.recordId || correction.reason.trim().length < 5) { toast.error('Informe um motivo com pelo menos 5 caracteres.'); return; } setBusy(true); try { const result = await refreshBookRecordOnServer({ recordId: correction.recordId, reason: correction.reason.trim() }); toast.success(`${result.attendances} atendimento(s) conferido(s).`); setCorrection(null); } catch (error) { console.error(error); toast.error(String(error?.message || '').includes('VOLUME_ARQUIVADO') ? 'Um volume assinado não pode ser alterado.' : 'Não foi possível atualizar o registro.'); } finally { setBusy(false); } };
  const archiveVolume = async () => { if (!archiveDraft?.file || archiveDraft.file.type !== 'application/pdf' || archiveDraft.file.size > 8 * 1024 * 1024) { toast.error('Selecione um PDF de até 8 MB.'); return; } if (!archiveDraft.signerPersonId || !/^\d{11}$/.test(archiveDraft.signerCpf.replace(/\D/g, '')) || !archiveDraft.confirmed) { toast.error('Informe a dirigente, o CPF completo e marque a confirmação.'); return; } setBusy(true); try { await archiveBookVolumeOnServer({ volumeId: archiveDraft.volumeId, signerPersonId: archiveDraft.signerPersonId, signerCpf: archiveDraft.signerCpf, signatureMethod: 'gov_br_manual', confirmed: true, pdfBase64: await fileAsBase64(archiveDraft.file) }); toast.success('PDF assinado arquivado definitivamente.'); setArchiveDraft(null); } catch (error) { console.error(error); const message = String(error?.message || ''); toast.error(message.includes('IDENTIDADE_DIRIGENTE_INVALIDA') ? 'O CPF não corresponde à dirigente selecionada.' : message.includes('PDF_SEM_ASSINATURA_DIGITAL') ? 'O PDF não contém uma assinatura digital detectável. Assine e baixe o arquivo pelo GOV.BR antes de anexar.' : 'Não foi possível arquivar o volume.'); } finally { setBusy(false); } };
  const download = async volume => { setBusy(true); try { const result = await getBookVolumeDownloadOnServer(volume.id); window.location.assign(result.url); } catch (error) { console.error(error); toast.error('Não foi possível baixar o arquivo.'); } finally { setBusy(false); } };
  const resetForHml = async volume => { if (!window.confirm(`Resetar a assinatura do Volume ${volume.numero} somente para novo teste em HML? O arquivo anterior será preservado no histórico.`)) return; setBusy(true); try { await resetArchivedBookVolumeForHmlOnServer(volume.id); toast.success(`Volume ${volume.numero} liberado para uma nova simulação.`); } catch (error) { console.error(error); toast.error('Não foi possível resetar este volume de homologação.'); } finally { setBusy(false); } };
  const verifyIntegrity = async volume => { setBusy(true); try { const result = await verifyBookVolumeIntegrityOnServer(volume.id); setIntegrityChecks(current => ({ ...current, [volume.id]: result.intact ? 'integro' : 'divergente' })); if (result.intact) toast.success(`Volume íntegro. Código ${result.verificationCode}.`); else toast.error('Foi encontrada uma divergência. O volume não poderá ser arquivado.'); } catch (error) { console.error(error); toast.error('Não foi possível verificar a integridade do volume.'); } finally { setBusy(false); } };

  return <div id="livro-mediunico" className="scroll-mt-24 space-y-4">
    <div><h3 className="flex items-center gap-2 font-black uppercase text-indigo-800"><BookOpen size={18}/> Volumes do Livro Mediúnico</h3><p className="mt-1 text-xs text-gray-500">Confira os registros antes de encerrar e assinar o volume mensal.</p></div>
    <div className="rounded-xl bg-blue-50 p-3 text-xs text-blue-900"><strong>Fechamento mensal automático</strong><p>Todo dia 1º, às 06h, o sistema encerra o volume do mês anterior. O botão manual permanece disponível como contingência.</p></div>
    {ordered.some(volume => volume.status === 'aberto' && volume.fechamentoAutomaticoErro) && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800"><AlertTriangle className="mr-1 inline" size={16}/>O fechamento automático falhou. Confira o volume aberto abaixo e utilize “Encerrar mês agora”.</div>}
    <div className="grid grid-cols-2 gap-2"><select value={yearFilter} onChange={event => setYearFilter(event.target.value)} className="rounded-xl bg-gray-50 p-3 text-sm"><option value="todos">Todos os anos</option>{years.map(year => <option key={year}>{year}</option>)}</select><select value={monthFilter} onChange={event => setMonthFilter(event.target.value)} className="rounded-xl bg-gray-50 p-3 text-sm"><option value="todos">Todos os meses</option>{Array.from({ length: 12 }, (_, index) => String(index + 1).padStart(2, '0')).map(month => <option key={month} value={month}>{new Date(2026, Number(month) - 1, 1).toLocaleDateString('pt-BR', { month: 'long' })}</option>)}</select></div>
    <section className="space-y-3 rounded-2xl border border-indigo-100 bg-indigo-50/50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-indigo-950">Resumo anual de {dashboardYear}</strong><span className="text-xs text-indigo-700">{annualTotals.records} fechamento(s) · {annualTotals.attendances} atendimento(s)</span></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-white p-2"><strong className="block text-base">{annualTotals.signed}</strong>assinados</span><span className="rounded-lg bg-white p-2"><strong className="block text-base text-amber-700">{annualTotals.pending}</strong>aguardando assinatura</span><span className="rounded-lg bg-white p-2"><strong className="block text-base">{annualMonths.filter(item => !item.volume).length}</strong>sem atendimento</span></div><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{annualMonths.map(item => { const status = !item.volume ? 'Sem atendimento' : item.volume.status === 'aberto' ? 'Aberto' : item.volume.status === 'arquivado' ? 'Assinado' : 'Pendente'; const color = !item.volume ? 'border-gray-200 bg-gray-50 text-gray-500' : item.volume.status === 'aberto' ? 'border-blue-300 bg-blue-50 text-blue-800' : item.volume.status === 'arquivado' ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-amber-300 bg-amber-50 text-amber-800'; return <button type="button" key={item.month} disabled={!item.volume} onClick={() => { setYearFilter(dashboardYear); setMonthFilter(item.month); setExpandedVolumeId(item.volume.id); }} className={`rounded-xl border p-2 text-left ${color} disabled:cursor-default`}><strong className="block uppercase">{item.label}</strong><span className="text-[10px] font-bold">{status}</span>{item.volume && <span className="block text-[10px]">{item.volume.quantidadeAtendimentos || 0} atend.</span>}</button>; })}</div></section>
    <div className="grid gap-2 sm:grid-cols-2"><Button variant="secondary" onClick={() => { try { printAnnualIndex(annualIndex, false); } catch { toast.error('Autorize a abertura da janela.'); } }}><FileDown size={16}/> Gerar prévia anual</Button><Button variant="success" disabled={!annualIndex.definitiveReady} onClick={() => { try { printAnnualIndex(annualIndex, true); } catch { toast.error('Autorize a abertura da janela.'); } }}><FileDown size={16}/> Gerar índice definitivo</Button></div>
    {!annualIndex.definitiveReady && <p className="rounded-lg bg-amber-50 p-2 text-xs font-bold text-amber-800">O índice definitivo será liberado quando todos os volumes com movimento do ano estiverem assinados. Pendentes: {annualIndex.pendingCount}.</p>}
    {open ? <div className="rounded-xl bg-indigo-50 p-3 text-sm"><strong>Volume {open.numero} — {monthLabel(open.competencia)}</strong><p>{open.quantidadeRegistros || 0} registro(s) · {open.quantidadeAtendimentos || 0} atendimento(s)</p><Button className="mt-3 w-full" variant="warning" busy={busy} onClick={executeClose}><LockKeyhole size={16}/> Encerrar mês agora</Button></div> : <div className="rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-800">O próximo fechamento abrirá automaticamente o volume do mês.</div>}
    {visibleVolumes.map(volume => {
      const volumeRecords = records.filter(record => record.volumeId === volume.id); const issueCount = volumeRecords.reduce((sum, record) => sum + recordIssues(record).length, 0); const expanded = expandedVolumeId === volume.id; const integrityStatus = integrityChecks[volume.id] || volume.ultimaVerificacaoIntegridade?.resultado;
      return <div key={volume.id} className="space-y-3 rounded-xl border border-gray-100 p-3 text-sm">
        <div className="flex flex-wrap justify-between gap-2"><div><strong>Volume {volume.numero} — {monthLabel(volume.competencia)}</strong><p className="text-xs text-gray-500">{volume.status === 'aberto' ? 'Aberto' : volume.status === 'arquivado' ? 'Assinado e arquivado' : 'Encerrado'} · {volumeRecords.length} registro(s)</p></div>{issueCount > 0 && <span className="flex items-center gap-1 text-xs font-bold text-amber-700"><AlertTriangle size={15}/>{issueCount} pendência(s)</span>}</div>
        <Button variant="secondary" className="w-full" onClick={() => setExpandedVolumeId(expanded ? '' : volume.id)}><Eye size={16}/>{expanded ? 'Ocultar conferência' : 'Conferir registros'}</Button>
        {volume.status !== 'aberto' && <><Button variant="secondary" className="w-full" busy={busy} onClick={() => verifyIntegrity(volume)}>{integrityStatus === 'divergente' ? <ShieldX size={16}/> : <ShieldCheck size={16}/>} Verificar integridade</Button>{integrityStatus && <div className={`rounded-lg p-2 text-xs font-bold ${integrityStatus === 'integro' ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-800'}`}>{integrityStatus === 'integro' ? 'Integridade confirmada.' : 'Divergência encontrada — arquivamento bloqueado.'}</div>}</>}
        {expanded && <div className="space-y-3">{volumeRecords.map(record => <div key={record.id} className="rounded-xl bg-gray-50 p-3"><strong>{formatDate(record.dataAtendimento)} · {record.trabalho}</strong><p className="text-xs text-gray-500">{record.quantidadeAtendimentos || 0} atendimento(s) · responsável: {record.dirigenteResponsavel?.nome || 'não informado'}</p>{recordIssues(record).map(issue => <p key={issue} className="mt-1 text-xs font-bold text-amber-700">⚠ {issue}</p>)}{(record.atendimentos || []).map(item => <p key={item.agendamentoId} className="mt-2 border-t border-gray-200 pt-2 text-xs"><strong>{item.nome}</strong> · {(item.servicos || []).map(service => service.nome).join(', ') || 'sem serviço'} · {item.status}<br/>Chegada {formatTime(item.horaChegada)} · conclusão {formatTime(item.horaConclusao)}</p>)}{volume.status !== 'arquivado' && <Button variant="ghost" className="mt-2 w-full" onClick={() => setCorrection({ recordId: record.id, reason: '' })}><RefreshCcw size={15}/> Atualizar a partir do atendimento</Button>}{correction?.recordId === record.id && <div className="mt-2 space-y-2"><textarea value={correction.reason} onChange={event => setCorrection({ ...correction, reason: event.target.value })} maxLength={500} placeholder="Motivo da conferência/correção" className="w-full rounded-lg bg-white p-2"/><div className="grid grid-cols-2 gap-2"><Button variant="secondary" onClick={() => setCorrection(null)}>Cancelar</Button><Button busy={busy} onClick={refreshRecord}>Confirmar</Button></div></div>}</div>)}</div>}
        {volume.status !== 'aberto' && <Button variant="secondary" className="w-full" onClick={async () => { try { await printVolume(volume, volumeRecords); } catch { toast.error('Não foi possível gerar o PDF. Autorize a abertura da janela.'); } }}><FileDown size={16}/> Gerar PDF</Button>}
        {volume.status === 'arquivado' && <><Button variant="success" className="w-full" disabled={busy} onClick={() => download(volume)}><Download size={16}/> Baixar PDF arquivado</Button><Button variant="secondary" className="w-full" onClick={() => { try { printSignatureReceipt(volume); } catch { toast.error('Autorize a abertura da janela.'); } }}><FileDown size={16}/> Gerar comprovante do arquivamento</Button>{isHmlEnvironment && <Button variant="warning" className="w-full" busy={busy} onClick={() => resetForHml(volume)}><RefreshCcw size={16}/> Resetar assinatura para teste (HML)</Button>}<div className="rounded-lg bg-emerald-50 p-2 text-xs"><strong>Dirigente declarada: {volume.assinatura?.nome}</strong><p>{formatDate(volume.assinadoEm)} · CPF final {volume.assinatura?.cpfFinal}</p><p>{volume.assinatura?.metodo === 'gov_br_manual' ? 'PDF assinado externamente pelo GOV.BR' : 'Registro anterior ao fluxo GOV.BR'}</p><p className="font-mono">{volume.assinatura?.codigoEvidencia || 'Registro anterior à versão 26D'}</p></div></>}
        {volume.status === 'encerrado' && (archiveDraft?.volumeId === volume.id ? <div className="space-y-2 rounded-xl bg-amber-50 p-3"><div className="rounded-lg bg-white p-3 text-xs"><strong>Fluxo GOV.BR</strong><ol className="mt-1 list-decimal space-y-1 pl-4"><li>Gere e salve o PDF deste volume.</li><li>Assine o arquivo no serviço oficial GOV.BR.</li><li>Baixe o PDF assinado e anexe abaixo.</li></ol><a href="https://www.gov.br/pt-br/servicos/assinatura-eletronica" target="_blank" rel="noreferrer" className="mt-2 inline-block font-bold text-indigo-700 underline">Abrir Assinatura Eletrônica GOV.BR</a></div><select value={archiveDraft.signerPersonId} onChange={event => setArchiveDraft({ ...archiveDraft, signerPersonId: event.target.value })} className="w-full rounded-lg bg-white p-3"><option value="">Dirigente que assinou</option>{eligibleSigners.map(person => <option key={person.id} value={person.id}>{person.nome}</option>)}</select><input value={archiveDraft.signerCpf} onChange={event => setArchiveDraft({ ...archiveDraft, signerCpf: event.target.value })} placeholder="CPF completo da dirigente" className="w-full rounded-lg bg-white p-3"/><input type="file" accept="application/pdf,.pdf" onChange={event => setArchiveDraft({ ...archiveDraft, file: event.target.files?.[0] || null })}/><label className="flex gap-2 text-xs"><input type="checkbox" checked={archiveDraft.confirmed} onChange={event => setArchiveDraft({ ...archiveDraft, confirmed: event.target.checked })}/>Confirmo que este é o PDF baixado após a assinatura no GOV.BR.</label><Button variant="success" className="w-full" busy={busy} onClick={archiveVolume}><Archive size={16}/> Verificar e arquivar PDF assinado</Button></div> : <Button variant="warning" className="w-full" onClick={() => setArchiveDraft({ volumeId: volume.id, signerPersonId: '', signerCpf: '', confirmed: false, file: null })}><Archive size={16}/> Assinar pelo GOV.BR e arquivar</Button>)}
      </div>;
    })}
  </div>;
};
