import React, { useEffect, useMemo, useState } from 'react';
import { CalendarPlus } from 'lucide-react';
import { createProgramacaoLote, getAppCollection, onSnapshot } from '../../services/firebase';
import { getPublicosPermitidosTrabalho, servicoControlaVagas, servicoPertenceAoTrabalho } from '../../utils/domain';
import { generateWeeklyRecurrence } from '../../utils/agendaScheduling';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { useToast } from '../../components/ui/useToast';
import { AgendaAdminCard } from '../Agendas/AgendaAdminCard';

const initialDraft = { mode: 'specific', tipoTrabalhoId: '', servicosIds: [], horario: '12:00', publicosPermitidos: [], vagasTotais: {}, dates: [], weekday: '3', startDate: '', endDate: '' };
const publicOptions = [{ id: 'consulente', nome: 'Consulentes' }, { id: 'membro', nome: 'Membros' }];
const weekdays = ['domingo', 'segunda-feira', 'terça-feira', 'quarta-feira', 'quinta-feira', 'sexta-feira', 'sábado'];
const displayDate = date => new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR');

export const ProgramacaoModule = ({ user, profile }) => {
  const [trabalhos, setTrabalhos] = useState([]); const [servicos, setServicos] = useState([]); const [agendas, setAgendas] = useState([]);
  const [draft, setDraft] = useState(initialDraft); const [newDate, setNewDate] = useState(''); const [saving, setSaving] = useState(false); const [preview, setPreview] = useState(false); const toast = useToast();
  useEffect(() => { const unsubs = [onSnapshot(getAppCollection('config_eventos'), snap => setTrabalhos(snap.docs.map(doc => ({ id: doc.id, ...doc.data() })).filter(item => item.ativo !== false))), onSnapshot(getAppCollection('config_servicos'), snap => setServicos(snap.docs.map(doc => ({ id: doc.id, ...doc.data() })).filter(item => item.ativo !== false))), onSnapshot(getAppCollection('agendas'), snap => setAgendas(snap.docs.map(doc => ({ id: doc.id, ...doc.data() }))))]; return () => unsubs.forEach(unsub => unsub()); }, []);
  const trabalho = trabalhos.find(item => item.id === draft.tipoTrabalhoId);
  const availableServices = useMemo(() => servicos.filter(item => servicoPertenceAoTrabalho(item, draft.tipoTrabalhoId)), [servicos, draft.tipoTrabalhoId]);
  const selectedServices = availableServices.filter(item => draft.servicosIds.includes(item.id));
  const recurrence = useMemo(() => { if (draft.mode !== 'recurrence' || !draft.startDate || !draft.endDate) return { dates: [], error: null }; try { return { dates: generateWeeklyRecurrence({ weekday: Number(draft.weekday), startDate: draft.startDate, endDate: draft.endDate }), error: null }; } catch (error) { return { dates: [], error: error.message }; } }, [draft.mode, draft.weekday, draft.startDate, draft.endDate]);
  const calculatedDates = draft.mode === 'specific' ? draft.dates : recurrence.dates;
  const recurrenceMessage = { DATA_FINAL_ANTERIOR: 'A data final não pode ser anterior à inicial.', RECORRENCIA_SEM_OCORRENCIA: 'O período não possui ocorrência para o dia escolhido.', PROGRAMACAO_DATA_PASSADA: 'A programação não pode incluir datas passadas.', RECORRENCIA_INVALIDA: 'Revise os campos da recorrência.' }[recurrence.error];
  const toggle = (field, id) => { setDraft(current => ({ ...current, [field]: current[field].includes(id) ? current[field].filter(item => item !== id) : [...current[field], id] })); setPreview(false); };
  const selectWork = id => { const selected = trabalhos.find(item => item.id === id); setDraft(current => ({ ...initialDraft, mode: current.mode, tipoTrabalhoId: id, publicosPermitidos: getPublicosPermitidosTrabalho(selected), horario: current.horario })); setPreview(false); };
  const addDate = () => { if (!newDate || draft.dates.includes(newDate)) return; setDraft(current => ({ ...current, dates: [...current.dates, newDate].sort() })); setNewDate(''); setPreview(false); };
  const review = () => { const today = new Date(); today.setHours(0, 0, 0, 0); if (!trabalho || !selectedServices.length || !calculatedDates.length || recurrence.error || calculatedDates.some(date => new Date(`${date}T12:00:00`) < today) || selectedServices.some(item => servicoControlaVagas(item) && Number(draft.vagasTotais[item.id] || 0) < 1)) { toast.error(recurrenceMessage || 'Revise trabalho, serviços, vagas e datas.'); return; } setPreview(true); };
  const save = async () => { setSaving(true); try { await createProgramacaoLote({ trabalho, servicos: selectedServices, horario: draft.horario, publicosPermitidos: draft.publicosPermitidos, vagasTotais: draft.vagasTotais, dates: calculatedDates, userId: user.uid }); toast.success(`${calculatedDates.length} data(s) programada(s) com sucesso.`); setDraft(initialDraft); setPreview(false); } catch (error) { console.error(error); if (error.message.startsWith('PROGRAMACAO_DUPLICADA:')) { const dates = error.message.split(':')[1].split(',').map(displayDate).join(', '); toast.error(`Conflito: estas datas já estão programadas: ${dates}. Nenhuma data foi criada.`); } else toast.error(error.message === 'PROGRAMACAO_DATA_PASSADA' ? 'A programação não pode incluir datas passadas.' : 'Não foi possível salvar a programação.'); } finally { setSaving(false); } };
  return <div className="space-y-6 pb-10"><header><h2 className="text-3xl font-black uppercase italic">Programação</h2><p className="text-sm text-gray-500">Disponibilidade da Casa para agendamentos</p></header><Card className="space-y-5">
    <h3 className="font-black uppercase text-amber-700 flex gap-2"><CalendarPlus size={18}/> Programar datas em lote</h3>
    <div><p className="text-xs font-black mb-2">Como deseja programar?</p><div className="grid grid-cols-2 gap-2">{[['specific', 'Datas específicas'], ['recurrence', 'Recorrência']].map(([id, label]) => <button key={id} onClick={() => { setDraft(current => ({ ...current, mode: id })); setPreview(false); }} className={`p-3 rounded-xl font-bold text-sm ${draft.mode === id ? 'bg-indigo-600 text-white' : 'bg-gray-100 text-gray-600'}`}>{label}</button>)}</div></div>
    <label className="block text-xs font-black">Tipo de Trabalho<select value={draft.tipoTrabalhoId} onChange={event => selectWork(event.target.value)} className="w-full bg-gray-50 p-3 rounded-xl mt-2"><option value="">Selecione</option>{trabalhos.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label>
    <div><p className="text-xs font-black mb-2">Serviços</p>{availableServices.map(item => <div key={item.id} className="bg-gray-50 rounded-xl p-3 mb-2"><label className="font-bold text-sm"><input type="checkbox" checked={draft.servicosIds.includes(item.id)} onChange={() => toggle('servicosIds', item.id)}/> {item.nome}</label>{draft.servicosIds.includes(item.id) && servicoControlaVagas(item) && <input type="number" min="1" value={draft.vagasTotais[item.id] || ''} onChange={event => { setDraft(current => ({ ...current, vagasTotais: { ...current.vagasTotais, [item.id]: Number(event.target.value) } })); setPreview(false); }} placeholder="Vagas por data" className="w-full bg-white p-2 rounded-lg mt-2"/>}</div>)}</div>
    <label className="block text-xs font-black">Horário<input type="time" value={draft.horario} onChange={event => { setDraft({ ...draft, horario: event.target.value }); setPreview(false); }} className="w-full bg-gray-50 p-3 rounded-xl mt-2"/></label>
    <div><p className="text-xs font-black mb-2">Público permitido</p>{publicOptions.map(item => <label key={item.id} className="mr-4 text-sm font-bold"><input type="checkbox" checked={draft.publicosPermitidos.includes(item.id)} onChange={() => toggle('publicosPermitidos', item.id)}/> {item.nome}</label>)}</div>
    {draft.mode === 'specific' ? <div><p className="text-xs font-black mb-2">Datas específicas</p><div className="flex gap-2"><input type="date" value={newDate} onChange={event => setNewDate(event.target.value)} className="flex-1 bg-gray-50 p-3 rounded-xl"/><Button type="button" onClick={addDate}>Adicionar</Button></div><div className="flex flex-wrap gap-2 mt-3">{draft.dates.map(date => <button key={date} onClick={() => { setDraft(current => ({ ...current, dates: current.dates.filter(item => item !== date) })); setPreview(false); }} className="bg-amber-50 text-amber-800 px-3 py-2 rounded-xl text-xs font-bold">{displayDate(date)} ×</button>)}</div></div> : <div className="grid sm:grid-cols-3 gap-3"><label className="text-xs font-black">Dia da semana<select value={draft.weekday} onChange={event => { setDraft({ ...draft, weekday: event.target.value }); setPreview(false); }} className="w-full bg-gray-50 p-3 rounded-xl mt-2">{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label><label className="text-xs font-black">Data inicial<input type="date" value={draft.startDate} onChange={event => { setDraft({ ...draft, startDate: event.target.value }); setPreview(false); }} className="w-full bg-gray-50 p-3 rounded-xl mt-2"/></label><label className="text-xs font-black">Data final<input type="date" value={draft.endDate} onChange={event => { setDraft({ ...draft, endDate: event.target.value }); setPreview(false); }} className="w-full bg-gray-50 p-3 rounded-xl mt-2"/></label>{recurrenceMessage && <p className="sm:col-span-3 text-sm text-rose-600 font-bold">{recurrenceMessage}</p>}</div>}
    {preview && <div className="bg-indigo-50 text-indigo-900 rounded-xl p-4 space-y-2"><p className="font-black">Serão criadas {calculatedDates.length} datas</p><p><strong>Tipo de Trabalho:</strong> {trabalho?.nome}</p><p><strong>Serviços:</strong> {selectedServices.map(item => item.nome).join(', ')}</p>{draft.mode === 'recurrence' && <><p><strong>Dia da semana:</strong> {weekdays[Number(draft.weekday)]}</p><p><strong>Período:</strong> {displayDate(draft.startDate)} a {displayDate(draft.endDate)}</p></>}<p><strong>Horário:</strong> {draft.horario}</p><p><strong>Quantidade de datas:</strong> {calculatedDates.length}</p><div className="flex flex-wrap gap-2">{calculatedDates.map(date => <span key={date} className="bg-white px-2 py-1 rounded-lg text-xs font-bold">{displayDate(date)}</span>)}</div></div>}
    <p className="text-xs text-gray-500">Cada data será salva como uma agenda independente.</p>{!preview ? <Button variant="warning" className="w-full" onClick={review}>Revisar Programação</Button> : <div className="flex gap-2"><Button variant="secondary" className="flex-1" onClick={() => setPreview(false)}>Voltar</Button><Button variant="warning" className="flex-1" disabled={saving} onClick={save}>{saving ? 'Salvando...' : 'Confirmar criação'}</Button></div>}
  </Card><section className="space-y-3"><h3 className="font-black uppercase text-gray-700">Datas programadas e histórico administrativo</h3>{[...agendas].sort((a, b) => (b.data?.toMillis?.() || 0) - (a.data?.toMillis?.() || 0)).map(item => <AgendaAdminCard key={item.id} agenda={item} agendas={agendas} user={user} profile={profile} servicosCatalogo={servicos} trabalhos={trabalhos}/>)}</section></div>;
};
